### ISSUE TITLE
[BUG] Explorer (file explorer) not spyable

### ISSUE THREAD

**Issue by m0lDaViA** [m417z/UWPSpy#6] opened 2024-08-23 23:36 UTC
I'm not even sure how i should describe this bug.
You can see it in the video. The file explorer is not spyable like this.
Only noticed on explorer.exe so far.

https://github.com/user-attachments/assets/f54a0349-5e9b-4ff0-8ffe-6c8cae5921cd

Edit: Sorry for the music, i didn't noticed as i thought the snipping tool would record without audio ...

**Comment by m417z** [comment] 2024-08-24 09:27
UWPSpy opens a window per thread in the target application. The UWPSpy window you're showing the the video is likely related to the window arrangement UI that shows up when a window is moved:

https://youtu.be/nxXsZnQEniA?feature=shared&t=24

You can just close this UWPSpy window and look for the window that's relevant to what you're trying to inspect, e.g. the taskbar.

**Comment by m0lDaViA** [comment] 2024-08-28 20:54
If i'm not mistaken this should be the window for the file explorer itself.
Or maybe i'm just dumb as i can't find the right one for the file explorer.

**Comment by m417z** [comment] 2024-08-28 20:56
File explorer windows are using WinUI 3, not UWP. Select WinUI 3 when selecting a process.

**Comment by m0lDaViA** [comment] 2024-09-01 22:57
> File explorer windows are using WinUI 3, not UWP. Select WinUI 3 when selecting a process.

That's what i did, the app is just called uwpspy ...

**Comment by m417z** [comment] 2024-09-01 23:28
Post a full video recording of what you're doing and what you're seeing, starting from launching UWPSpy.

**Comment by LukaszPiatkowski27** [comment] 2024-09-29 15:31
Hi @m417z the OP's description is not matching my case, although I'm unable to spy on the file explorer as well.
When I try to spy on explorer.exe I get the error "Failed to start spying: Couldn't find the element. Make sure that the target process is a WinUI 3 application" even though I have the file explorer window open. The UWP works fine

**Comment by m417z** [comment] 2024-09-29 17:20
@LukaszPiatkowski27 Indeed, your issue seems to be unrelated to this issue. Perhaps your Windows 11 build is too old or too new. What build are you trying it on?

**Comment by LukaszPiatkowski27** [comment] 2024-10-02 18:21
@m417z 
Windows 11 Pro 23H2
Compilation No. 22631.3880

**Comment by m417z** [comment] 2024-10-02 18:45
@LukaszPiatkowski27 it should work, I have no immediate ideas why it doesn't. Maybe you have some flags which still use the old explorer version, without WinUI 3. If you could make a video recording of what exactly you're trying to do it might give some ideas. In any case, better do it in a new issue since it's not related to this one.

**Comment by m417z** [comment] 2024-10-18 22:09
@LukaszPiatkowski27 I was able to reproduce this issue in Windows 11 24H2, and I added a workaround in v1.3. Try it and let me know if it works.

I believe that the original report was about a different issue, but since there's no reply from the author, I'm closing it.

**Closed by m417z** 2024-10-18 22:09 UTC
